### ISSUE TITLE
Service resource not found

### ISSUE THREAD

**Issue by adamburns7933** [amalucelli/chef-cloudwatchlogs#5]
With Chef 12.5 I get this error:

```
Chef::Exceptions::ResourceNotFound: resource template[/var/awslogs/etc/config/archive_to_s3.conf] is configured to notify resource service[awslogs] with action restart, but service[awslogs] cannot be found in the resource collection.
```

Based on [this issue](https://github.com/chef/chef/issues/4410) I think this is likely a new error that start in this version of the Chef client. From [notes by the backslasher](http://blog.backslasher.net/chef-inline.html) (a community member I've found really knows their stuff), the solution is to define the service resource directly in the custom resource.

It's a simple fix and I've tested it in the situation I encountered. I'll submit a PR in a minute. Thanks!

Adam

**Comment by amalucelli** [comment]
Hi @operatingops, sorry for the late review. I couldn't reproduce this error, but your explanation makes sense, your PR LGTM!

**Comment by adamburns7933** [comment]
No worries @amalucelli, you're way faster than most OSS projects - thanks for the merge!
