### ISSUE TITLE
template.conf.erb template

### ISSUE THREAD

**Issue by jhmartin** [amalucelli/chef-cloudwatchlogs#7]
I don't see anything in here that describes the desired structure of template.conf.erb.

**Comment by amalucelli** [comment]
This recipie follow the supported configurations supported by the agent. You can check those configurations in the [docummentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html).

Also the `template.conf.erb` is used to create different stream configurations for various components independently, in a compartmentalize structure. More info [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html#create-additional-configuration-files).

**Comment by amalucelli** [comment]
Basically we get any key/value defined in the variable and put into the file, so it also can contain a invalid option as we don't validate those _(as this is not a official project, we don't know when they may change the confs)_.

This provider is responsible for that:
https://github.com/amalucelli/chef-cloudwatchlogs/blob/22357eceed56500211a4f608ec73994665c9a922/providers/aws_cwlogs.rb#L28-L38

**Comment by jhmartin** [comment]
My concern is that  the provider is expecting a `template.conf.erb` in the calling cookbook, but nothing in the README mentions this requirement --  so someone invoking the recipe would get an error.

**Comment by amalucelli** [comment]
The `template.conf.erb` is stored in `templates/default/template.conf.erb`, so it's not a requirement, this cookbook handle this file.

How are you using this cookbook?

**Comment by jhmartin** [comment]
Somehow I managed to not see the folder there even though I was specifically looking for it. I apologize for the confusion.
